### ISSUE TITLE
Support pull request reviews

### ISSUE THREAD

**Issue by mscharley** [47deg/github4s#133]
I've been using this library and really like it but I need access to pull request reviews, at least read-only access. How hard would it be to add this?

**Comment by BenFradet** [comment]
I'm currently writing a guilde about this and it basically boils down to:

- Add a model of the github responses you're expecting in [`github4s.free.domain`](https://github.com/47deg/github4s/tree/master/github4s/shared/src/main/scala/github4s/free/domain/PullRequest.scala)
- Add a corresponding algebra in [`github4s.free.algebra`](https://github.com/47deg/github4s/blob/master/github4s/shared/src/main/scala/github4s/free/algebra/PullRequestOps.scala) (e.g. `GetReview`)
- Make the interpreter in [`github4s.free.interpreter`](https://github.com/47deg/github4s/blob/master/github4s/shared/src/main/scala/github4s/free/interpreters/Interpreters.scala#L280-L314) aware of your algebra
- Create a method actually making the call in [`github4s.api`](https://github.com/47deg/github4s/blob/master/github4s/shared/src/main/scala/github4s/api/PullRequests.scala)
- Add the corresponding method to [`GithubAPIs`](https://github.com/47deg/github4s/blob/master/github4s/shared/src/main/scala/github4s/GithubAPIs.scala#L294-L318)
- Add integration tests (https://github.com/47deg/github4s/blob/master/github4s/shared/src/test/scala/github4s/integration/GHPullRequestsSpec.scala) except for endpoints creating stuff (e.g. don't make an integration test for the create review endpoint.
- Add unit tests:
  - https://github.com/47deg/github4s/blob/master/github4s/shared/src/test/scala/github4s/unit/GHPullRequestsSpec.scala
  - https://github.com/47deg/github4s/blob/master/github4s/shared/src/test/scala/github4s/unit/PullRequestsSpec.scala
- Add JVM-specific unti tests https://github.com/47deg/github4s/blob/master/github4s/jvm/src/test/scala/github4s/unit/ApiSpec.scala

**Comment by BenFradet** [comment]
Also as a last step, you can add to the documentation :+1:

**Comment by mscharley** [comment]
I'm going to start taking a look at this tomorrow.
