### ISSUE TITLE
Integration tests create a bunch of gists

### ISSUE THREAD

**Issue by mscharley** [47deg/github4s#149]
Not sure if this is a bug or not, but one of the integration tests seems to be creating a gist every time it's run... I ended up with 30~40 gists on my account without even realising it while working on #139 and #142 which was... annoying.

**Comment by BenFradet** [comment]
ahah just noticed it too, we'll have to remove those.

**Comment by juanpedromoreno** [comment]
Agreed

**Comment by BenFradet** [comment]
solved in #151 :+1:
