### ISSUE TITLE
Make the integration tests skippable

### ISSUE THREAD

**Issue by BenFradet** [47deg/github4s#178]
This is needed for scala/community-builds#621

**Comment by SethTisue** [comment]
fwiw, I'm still interested in this

**Comment by BenFradet** [comment]
I'll try having a stab later today :+1:

**Comment by SethTisue** [comment]
how do I tell sbt to run only the non-integration tests?

**Comment by BenFradet** [comment]
they will automatically be skipped based on the absence of the `GITHUB4S_ACCESS_TOKEN` environment variable.

**Comment by SethTisue** [comment]
cool! trying it out at https://github.com/scala/community-build/pull/1054
