### ISSUE TITLE
Add function to get a single issue

### ISSUE THREAD

**Issue by GRBurst** [47deg/github4s#185]
Hi,

I would be happy if a function is added to get a single issue. There is a [specific GitHub api call](https://developer.github.com/v3/issues/#get-a-single-issue) for that.

Currently I fetch all issues of a repo and filter the number to achive that, but this is not as convenient as it can be :-)

Kind regards

**Comment by BenFradet** [comment]
Hey @GRBurst , feel free to open a PR, there is [a contributing guide](http://47deg.github.io/github4s/contributing.html) that might help you along the way 👍

**Comment by GRBurst** [comment]
@BenFradet What method name would you prefer, `getIssue` or just `get`?
How is Travis going?

**Comment by juanpedromoreno** [comment]
Hi @GRBurst , I did some progress here: https://github.com/47deg/github4s/pull/190

Hopefully, that solves the issue.
