### ISSUE TITLE
Unit tests are failing on Travis but not locally

### ISSUE THREAD

**Issue by BenFradet** [47deg/github4s#189]
e.g. https://travis-ci.org/47deg/github4s/builds/326316681 but I can't reproduce them locally.

Is it possible that the permissions for the token used during CI have been changed?

cc @juanpedromoreno

**Comment by juanpedromoreno** [comment]
Probably, before resetting tokens, I've sent out this PR just in case the issue is due to Travis environment issues: https://github.com/47deg/github4s/pull/190

**Comment by juanpedromoreno** [comment]
With that small change, tests seem to pass. However, it's failing in the JS part, and builds are aborted after 10 minutes without any new output. I'll take a look at it tomorrow.

**Comment by juanpedromoreno** [comment]
PR updated: https://github.com/47deg/github4s/pull/190

**Comment by BenFradet** [comment]
closing thanks to #190, thanks @juanpedromoreno !
