### ISSUE TITLE
Pagination for ListPullRequests and ListPullRequestFiles

### ISSUE THREAD

**Issue by lloydmeta** [47deg/github4s#197]
Please correct me if I'm wrong, but it doesn't look like any of the pull-request listing ops allow for pagination, e.g.

https://github.com/47deg/github4s/blob/89e9dfb7d0b12d230acb5e227a6e069c5656ae7d/github4s/shared/src/main/scala/github4s/free/algebra/PullRequestOps.scala#L29-L41

**Comment by BenFradet** [comment]
True, feel free to open a PR! :+1:
