### ISSUE TITLE
Scala 2.13 Release

### ISSUE THREAD

**Issue by ChristopherDavenport** [47deg/github4s#261]
A lot of project use this to publish microsites. Would be nice to be able to have the docs directory of repos using this with sbt-microsites be able to have their docs in the aggregated build, by being able to cross-version this dep for the time being.

Present workaround is to exclude docs from aggregated build, and only run docs commands on scala <= 2.12

**Comment by bilki** [comment]
Hey @ChristopherDavenport I'm not sure I'm understanding the problem. Could you expand a bit more the description with an example, please?

**Comment by bilki** [comment]
I'm trying to cross-build a `2.13` release right now, by the way.

**Comment by SethTisue** [comment]
I see the PR was merged. I'd be interested in having a release, as well.

**Comment by calvellido** [comment]
Sadly not yet @SethTisue, the PR merged was an external one, not the one updating GitHub4s:

https://github.com/47deg/github4s/pull/262

@bilki found some setbacks on the way, which I think it's mainly this dependency update:

https://github.com/hmil/RosHTTP/pull/88

Thanks!
