### ISSUE TITLE
Replace HTTP client/server library

### ISSUE THREAD

**Issue by rafaparadela** [47deg/github4s#332]
Given that we want to let the users of GitHub4s decide what `[F]` target monad they want to use to perform the HTTP calls to GitHub, it would be more convenient to replace [`scalaj-http`](https://github.com/scalaj/scalaj-http) by [`http4s`](https://http4s.org/) which fits perfectly with this approach.

**Comment by juanpedromoreno** [comment]
Closed by https://github.com/47deg/github4s/pull/344
