### ISSUE TITLE
Lower code coverage threshold

### ISSUE THREAD

**Issue by BenFradet** [47deg/github4s#349]
Without access to the token (e.g. with scala-steward), the code coverage falls below 80% (77.74% to be precise) and the CI fails.

e.g. https://travis-ci.org/47deg/github4s/jobs/653257784#L1057

We could lower the threshold to 75% so that external PRs succeed CI.

**Comment by cb372** [comment]
That sounds reasonable. I have to say, on most of our repos the code coverage checker seems to cause more trouble than it's worth.
