### ISSUE TITLE
Update documentation / microsite

### ISSUE THREAD

**Issue by jdesiloniz** [47deg/github4s#42]
We should take some time to update the docs and the microsite to reflect the changes that have been included in the library, maybe splitting the docs in several sections for the JVM and JS case uses.

**Comment by icassina** [comment]
how do you list pull requests with this library? no idea what the syntax is.

**Comment by fedefernandez** [comment]
You're right, one of the main flaws of this project is the documentation. I'll try to, at least, organize the issues for documenting all operations.

In the meantime, you can always take a look at the tests where most of the operations are tested. For example, [here](https://github.com/47deg/github4s/blob/master/github4s/jvm/src/test/scala/github4s/integration/GHPullRequestsSpec.scala#L34-L41) there is an example of how to list the pull requests using the `Id` monad. You've implicits for `Id`, `Eval` and `Future`, as you can see [here](https://github.com/47deg/github4s/blob/master/github4s/shared/src/main/scala/github4s/Implicits.scala)

**Comment by BenFradet** [comment]
I'm planning on continuing to document the other APIs as well :+1:

**Comment by juanpedromoreno** [comment]
I believe this issue is almost done. I'd suggest doing a general editorial review of the documentation though, before releasing the `0.15.0` version. CC @anamariamv

**Comment by anamariamv** [comment]
@MaureenElsberry could you review the [documentation](https://github.com/47deg/github4s/tree/master/docs/src/main/tut), before releasing the 0.15.0, please?
