### ISSUE TITLE
Create package object to handle current imports

### ISSUE THREAD

**Issue by jdesiloniz** [47deg/github4s#45]
There are a lot of imports needed to perform actions on the API (i.e.: Interpreters.scala). We should have a package object to handle these as type aliases, so users can just import that to get started using them.

**Comment by bilki** [comment]
Hey, @jdesiloniz is this still a thing we need to do?

**Comment by jdesiloniz** [comment]
@bilki I think we can close this, I was playing with github4s yesterday a little bit and this doesn't seem to be an issue anymore.
