### ISSUE TITLE
Implement the library using freestyle

### ISSUE THREAD

**Issue by ghost** [47deg/github4s#57]
For aligning its dependencies with other libraries/applications using [freestyle](http://github.com/47deg/freestyle) and so it can be combined with other freestyle algebras and interpreters.

**Comment by AdrianRaFo** [comment]
sbt does not support plugins in 2.10 version and we need 2.11 minimun version for freestyle integration

**Comment by juanpedromoreno** [comment]
This should be now unblocked since our plugins now support scala 2.12.

**Comment by suhasgaddam** [comment]
If `github4s` stops publishing scala 2.10 artifacts, `sbt-org-policies` needs to move away from `github4s` for its sbt 0.13 plugin(or drop sbt 0.13 support).

**Comment by juanpedromoreno** [comment]
At some point, I guess that is something inevitable.
