### ISSUE TITLE
Random issues on Travis

### ISSUE THREAD

**Issue by fedefernandez** [47deg/github4s#84]
We have a lot of errored builds in Travis due to inactivity when executing:
*  `Fast optimizing /home/travis/build/47deg/github4s/github4s/js/target/scala-2.12/github4s-test-fastopt.js`

See an [example here](https://travis-ci.org/47deg/github4s/jobs/218842446#L1828)

**Comment by BenFradet** [comment]
I also got a few of those when running the tests locally.
